defaults:
  - operation-segmentation
  - _self_
issue: "I01-EXP1-V1"
model:
  name: DeepConvLSTM-SelfAttn
  cnn_filters: 64
  lstm_units: 128
  num_attn_heads: 8
train:
  num_workers: 3
  batch_size: 8
  epochs: 200
  window: 1800 # 30Hz * 60s
  optimizer:
    type: "Adam"
    lr: 0.001
    weight_decay: 0.0001
  debug:
    batch_size: 8
    epochs: 5
